-- Product catalog schema.
--
-- The CHECK constraints deliberately mirror the bean-validation rules on the API DTOs. Validation
-- gives callers a helpful 400; the constraints make the rules true of the data itself, including for
-- rows written by a migration, a backfill script or a future second service.

CREATE TABLE products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200)  NOT NULL,
    -- NUMERIC, never a float: money must not be subject to binary rounding.
    price      NUMERIC(12, 2) NOT NULL,
    category   VARCHAR(100)  NOT NULL,
    quantity   INTEGER       NOT NULL,
    -- Optimistic locking counter maintained by Hibernate's @Version.
    version    BIGINT        NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT ck_products_name_not_blank        CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_products_category_not_blank    CHECK (length(btrim(category)) > 0),
    CONSTRAINT ck_products_price_positive        CHECK (price > 0),
    CONSTRAINT ck_products_quantity_non_negative CHECK (quantity >= 0)

);

-- Product names are unique case-insensitively. Enforced here rather than with a read-then-write
-- check in the service, which would be a lost race under concurrency.
CREATE UNIQUE INDEX ux_products_name_lower ON products (lower(name));

COMMENT ON TABLE products IS 'Products offered in the catalog';
COMMENT ON COLUMN products.version IS 'Optimistic locking version, incremented on every update';
